# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/akaihola/darker
    rev: v3.0.0
    hooks:
    - id: darker
      args:
        - --line-length=120
      additional_dependencies:
        - black

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: [ --profile=black ]
